### ISSUE TITLE
Successfully created s3_admin_user, fails to create  buckets

### ISSUE THREAD

**Issue by KrisBuytaert** [yomovh/tf-at-ovhcloud#4]
I followed the readme .. and while tf seems to be able to create an s3_admin_user , and set it's credentials 
it doesn't create  the actuall bucket.

ovh_cloud_project_user.s3_admin_user: Creating...
ovh_cloud_project_user.s3_admin_user: Still creating... [10s elapsed]
ovh_cloud_project_user.s3_admin_user: Creation complete after 14s [id=346466]
ovh_cloud_project_user_s3_credential.s3_admin_cred: Creating...
ovh_cloud_project_user_s3_credential.s3_admin_cred: Creation complete after 0s [id=eb80f35a361b4b4a8259ac178a35eb72]
╷
│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ AWS Error: failed to refresh cached credentials, static credentials are empty
│
│
│   with provider["registry.opentofu.org/hashicorp/aws"],
│   on s3_bucket_only.tf line 61, in provider "aws":
│   61: provider "aws" {
│
╵

Not sure what causes this..

**Comment by yomovh** [comment]
Thanks for this issue that is related to that [one](https://github.com/ovh/terraform-provider-ovh/issues/490)

The fix is available in version [0.35.0](https://github.com/ovh/terraform-provider-ovh/releases/tag/v0.35.0)
Since my examples are not specifying a specific version of the provider, if you run  `terraform init --upgrade` it should pull the newer version and you should be good to run  `terraform apply`

**Comment by KrisBuytaert** [comment]
Yes, correct ... I did an upgrade of the provider and it now works .
